### ISSUE TITLE
system/core/rootdir/init.rc中service celld /system/bin/celld，这个celld binary文件有吗？对应的源码有吗？

### ISSUE THREAD

**Issue by shihaikuo** [jianglin-code/cells-android10#3]
您好：
    初步查看代码，当前代码创建的容器可能基于celld进行实现，看到service celld服务，但是对应的binary没有，该服务没有用吗？
还是怎样？谢谢！

system/core/rootdir/init.rc:862:service celld /system/bin/celld -c /data/cells -s /data/cells_sd -F -r

**Comment by jianglin-code** [comment]
celld源码在顶层目录cells中。

**Comment by shihaikuo** [comment]
找到了，多谢！
看当前代码，commit信息不是很清晰，要找出哪些是新增修改可能要费些时间了。您本地，有android10原始代码，基于这个基础，然后进行commit的吗？

**Comment by jianglin-code** [comment]
The Android source code is:  android-10.0.0_r33

**Comment by shihaikuo** [comment]
感谢感谢！

**Comment by shihaikuo** [comment]
update，下载android-10.0.0_r33代码方法(网络可以访问才行)：
repo init -u https://android.googlesource.com/platform/manifest
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r33
repo sync -c

**Comment by jianglin-code** [comment]
建议切换到国内镜像站点




| |
江淋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月14日 11:15，Hank.shi 写道：

update，下载android-10.0.0_r33代码方法(网络可以访问才行)：
repo init -u https://android.googlesource.com/platform/manifest
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r33

**Comment by shihaikuo** [comment]
kernel 部分代码看Makefile是v4.9.200的代码吧？ 
我从linux官网git clone下来的代码和你的kernel部分对比，有很大差异。是我我下载错了，还是确实有这么多修改？

git clone --depth=1 --branch v4.9.200 https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux.git

谢谢！

**Comment by jianglin-code** [comment]
kernel目录仅包括内核源码，不包括编译工程。




| |
江淋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月14日 14:23，Hank.shi 写道：

kernel 部分代码看Makefile是v4.9.200的代码吧？
我从linux官网git clone下来的代码和你的kernel部分对比，有很大差异。是我我下载错了，还是确实有这么多修改？

git clone --depth=1 --branch v4.9.200 https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux.git

谢谢！

**Comment by shihaikuo** [comment]
cells-of-Android 项目有讲 kernel部分需要做如下修改：3)、veth.c --- wlan、rmnt_data 网络虚拟化必备“网线”， 请根据最新版本内核更新一下此设备，网络虚拟化借鉴了“usb共享网络”的原理

但是cells-of-Android10 通过对比kernel代码，发现veth.c并没有差异，在10上面不需要修改了吗 ？

谢谢！

**Comment by jianglin-code** [comment]
是的




| |
江淋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月16日 16:46，Hank.shi 写道：

cells-of-Android 项目有讲 kernel部分需要做如下修改：3)、veth.c --- wlan、rmnt_data 网络虚拟化必备“网线”， 请根据最新版本内核更新一下此设备，网络虚拟化借鉴了“usb共享网络”的原理

但是cells-of-Android10 通过对比kernel代码，发现veth.c并没有差异，在10上面不需要修改了吗 ？

谢谢！

**Comment by shihaikuo** [comment]
3、位于kernel目录下的drivers目录
  4)、alarm-dev.c --- alarm 驱动隔离
3、位于hardware目录下的libhardware_legacy目录
    1)、power.c --- wakelock 虚拟化，核心：各系统wakelock不能重命名，改名！

这两个android10也没要，同样不需要修改了对吧？ 是不是按照android10的来，理论上是可行的？
另外android10上面的代码，本地测试可以进行切换系统的对吧 ？

谢谢！

**Comment by jianglin-code** [comment]
是的




| |
江淋
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月16日 17:02，Hank.shi 写道：

3、位于kernel目录下的drivers目录
4)、alarm-dev.c --- alarm 驱动隔离
3、位于hardware目录下的libhardware_legacy目录
1)、power.c --- wakelock 虚拟化，核心：各系统wakelock不能重命名，改名！

这两个android10也没要，同样不需要修改了对吧？ 是不是按照android10的来，理论上是可行的？
另外android10上面的代码，本地测试可以进行切换系统的对吧 ？

谢谢！

**Comment by shihaikuo** [comment]
你好： 再咨询个问题，基于lxc容器新一个android系统，针对data分区这块如何处理的？两个系统data分区都要加密，这块系统自动完成的？ 比如基于/data/lxc/root目录新建容器，vold需要做适配修改吗？

谢谢！
