### ISSUE TITLE
代码对应的真机？

### ISSUE THREAD

**Issue by purplepalmdash** [jianglin-code/cells-android10#4]
从kernel的改动记录来看，
bonito_defconfig是说这份代码针对的是pixel 3a/3a XL做的吗?

我在android studio模拟器的内核代码上加上`https://github.com/jianglin-code/cells-android10/commit/d9430898bbc32e4169510da47ef54b9386a40fd0#diff-6923dd1bc0460082c5d55a831908c24a282860b7f1cd6c2b79cf1bc8857c639c`对应的修改，aosp代码加上framework及system更改后启动cells，结果卡在启动的bootlogo，这种情况应该可以从何处着手排除问题？

**Comment by jianglin-code** [comment]
bonito_defconfig是说这份代码针对的是pixel 3a/3a XL做的吗? ---是的

**Comment by purplepalmdash** [comment]
多谢解答。
卡在bootlogo是权限问题所导致：

```
# vim frameworks/base/data/etc/privapp-permissions-platform.xml
添加: 
    <privapp-permissions package="com.cells.cellswitch.secure">
        <permission name="android.permission.BLUETOOTH_PRIVILEGED"/>
    </privapp-permissions>
```
`cells-android10`这个项目很棒，加油！
