### ISSUE TITLE
kernel evdev.c中没有is_active_evdev_drv_ns这个函数？

### ISSUE THREAD

**Issue by shanzhijian** [jianglin-code/cells-android10#6]
在evdev.c中的static bool evdev_client_is_active()函数中，使用了is_active_evdev_drv_ns(client->evdev_ns)，找了整个工程没有发现is_active_evdev_drv_ns

**Comment by jianglin-code** [comment]
这个函数由宏生成。














在 2022-03-14 16:08:13，"shanzhijian" ***@***.***> 写道：

在evdev.c中的static bool evdev_client_is_active()函数中，使用了is_active_evdev_drv_ns(client->evdev_ns)，找了整个工程没有发现is_active_evdev_drv_ns

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shanzhijian** [comment]
> 这个函数由宏生成。 在 2022-03-14 16:08:13，"shanzhijian" ***@***.***> 写道： 在evdev.c中的static bool evdev_client_is_active()函数中，使用了is_active_evdev_drv_ns(client->evdev_ns)，找了整个工程没有发现is_active_evdev_drv_ns — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

请问这个宏在哪里啊，实在是没有找到
